In [1]:
import torch

/home/ishans996/myProjects/rawnit_sawhney_defi_task/venv/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
import torch.nn as nn

In [22]:
import numpy as np

In [39]:
x = torch.tensor([ 0.0005,
        -0.0056,
        -0.0127, 
        np.NINF
                 ])

In [40]:
exp = torch.exp(x)

In [42]:
t = exp / torch.sum(exp)

In [43]:
t

tensor([0.3355, 0.3334, 0.3311, 0.0000])

In [45]:
t[-1] = np.nan

In [46]:
t

tensor([0.3355, 0.3334, 0.3311,    nan])

In [48]:
torch.where(torch.isnan(t), torch.tensor(0, dtype=torch.float32), t)

tensor([0.3355, 0.3334, 0.3311, 0.0000])